/* Hanaseru 辞書データ（Vault 20_診療英語 / 21_旅行日常 から抽出）
   1カード = { id, domain, ja, en, note }
   domain: sign(署名フレーズ) / medical(診療) / travel(旅行・日常)
   ※ 辞書を育てたら、この配列に足す（または Vault からの変換で再生成）。 */
window.HANASERU_CARDS = [
  // ── 署名フレーズ（辞書の背骨・軸）────────────────
  { id: "sign-01", domain: "sign", ja: "ご心配ですよね。お気持ちわかります。", en: "I understand you must be worried." },
  { id: "sign-02", domain: "sign", ja: "まず、安心してください。", en: "First, I want to reassure you." },
  { id: "sign-03", domain: "sign", ja: "これは子どもによくあることです。", en: "This is very common in children." },
  { id: "sign-04", domain: "sign", ja: "本当の◯◯ではありません。むしろ△△です。", en: "It isn't true ___. Rather, it's ___." },
  { id: "sign-05", domain: "sign", ja: "一番大事なのは、〜です。", en: "The most important thing is that ___." },
  { id: "sign-06", domain: "sign", ja: "その都度、しっかり治していきましょう。", en: "Let's treat it properly each time." },
  { id: "sign-07", domain: "sign", ja: "一緒に様子を見ていきましょう。", en: "Let's see how she's doing — together." },
  { id: "sign-08", domain: "sign", ja: "ですから、心配いりません。", en: "So, there's no need to worry." },
  { id: "sign-09", domain: "sign", ja: "何かあれば、いつでも来てください。", en: "If anything comes up, please come back anytime." },
  { id: "sign-10", domain: "sign", ja: "焦らず、少しずつ良くしていきましょう。", en: "Let's take it step by step and get her better." },

  // ── 診療英語 ───────────────────────────────
  { id: "med-intro-1", domain: "medical", ja: "私は小児外科医です。子どものお腹と栄養を診ています。", en: "I'm a pediatric surgeon. I look after children's gut health and nutrition." },
  { id: "med-intro-2", domain: "medical", ja: "今日はお子さんの状態を説明して、一緒に方針を決めましょう。", en: "Today I'll explain how your child is doing, and we'll decide the plan together." },
  { id: "med-ast-1", domain: "medical", ja: "熱と咳、ゼーゼーが続いて、ご心配ですよね。", en: "The fever, the cough, the wheezing — I know this is worrying." },
  { id: "med-ast-2", domain: "medical", ja: "まず安心してください。RSウイルスの検査は陰性でした。", en: "First, some reassurance: the RS virus test came back negative." },
  { id: "med-ast-3", domain: "medical", ja: "子どもは風邪をひくと、気道が敏感になってゼーゼーします。", en: "When children catch a cold, their airways get sensitive and they wheeze." },
  { id: "med-ast-4", domain: "medical", ja: "喘息のように聞こえますが、本当の喘息ではありません。", en: "It sounds like asthma, but it isn't true asthma." },
  { id: "med-ast-5", domain: "medical", ja: "酸素の値は問題ありません。ただ、ゼーゼーで夜眠りにくくなります。", en: "Her oxygen levels are fine, but the wheezing can make it hard to sleep at night." },
  { id: "med-ast-6", domain: "medical", ja: "クリニックで吸入をしました。気道を広げて楽にする薬です。", en: "We gave her an inhalation here — it opens the airways and makes breathing easier." },
  { id: "med-ast-7", domain: "medical", ja: "長く続く治療は要りません。風邪のたびにしっかり治すことが大事です。", en: "She doesn't need long-term treatment. What matters is treating each cold thoroughly." },
  { id: "med-ast-8", domain: "medical", ja: "今すぐ「喘息」と決めつける必要はありません。", en: "We don't need to label this as asthma right now." },
  { id: "med-ast-9", domain: "medical", ja: "大事なのは診断名より、今の気道の炎症をしっかり取ることです。", en: "What matters more than a label is calming the airway inflammation right now." },
  { id: "med-ast-10", domain: "medical", ja: "炎症をしっかり取ってリセットすると、本人も楽になり、次のゼーゼーの予防にもなります。", en: "Once we settle the inflammation and reset it, she'll feel better — and it helps prevent the next flare-up." },
  { id: "med-ast-11", domain: "medical", ja: "目標はシンプルです。夜ぐっすり眠れて、楽に呼吸できること。", en: "The goal is simple: she sleeps well at night and breathes easily." },
  { id: "med-med-1", domain: "medical", ja: "今の風邪薬は続けてください。今日、追加でお出しします。", en: "Please keep giving the current cold medicine — I'll refill it today." },
  { id: "med-med-2", domain: "medical", ja: "熱が数日続いて、中耳炎と軽い気管支炎が出ています。", en: "The fever has lasted a few days, so she's developed an ear infection and mild bronchitis." },
  { id: "med-med-3", domain: "medical", ja: "なので抗生物質を新しく足します。両方きちんと飲ませてください。", en: "So I'm adding an antibiotic. Please give both as prescribed." },
  { id: "med-med-4", domain: "medical", ja: "まずは熱が下がるか、鼻や胸の症状が良くなるかを見ていきましょう。", en: "First, let's see the fever come down and the runny nose and congestion improve." },
  { id: "med-rev-1", domain: "medical", ja: "熱が下がらなければ、木曜か金曜にまた来てください。", en: "If the fever doesn't come down, please come back this Thursday or Friday." },
  { id: "med-rev-2", domain: "medical", ja: "夜、咳がひどい時は、予約なしで吸入に来られます。この特急券をどうぞ。", en: "If the cough is bad at night, you can come for an inhalation without an appointment — here's an express ticket." },
  { id: "med-rev-3", domain: "medical", ja: "これだけは救急へ：横になって全く眠れない。", en: "Go straight to the ER if she simply can't sleep lying down." },
  { id: "med-rev-4", domain: "medical", ja: "肩やお腹を使って息をしている。目がうつろ。", en: "…or she's using her shoulders or belly to breathe, or her eyes look dazed." },
  { id: "med-fev-1", domain: "medical", ja: "集団生活を始めた子が、毎週のように風邪をひくのは、異常ではありません。", en: "It's completely normal for a child who's just started daycare to catch colds almost every week." },
  { id: "med-fev-2", domain: "medical", ja: "今は、体が初めてのウイルスに出会って、免疫を一つずつ学んでいる最中です。", en: "Right now her body is meeting new viruses for the first time and learning its immunity, one by one." },
  { id: "med-fev-3", domain: "medical", ja: "3ヶ月から半年ほどで、少しずつ強くなって山を越えます。", en: "Over about three to six months, she'll gradually get stronger and turn the corner." },
  { id: "med-fev-4", domain: "medical", ja: "完治を狙わなくて大丈夫。つらい症状を楽にしながら、根気よく付き合いましょう。", en: "We don't need to aim for a perfect cure. Let's ease the tough symptoms and stay patient together." },
  { id: "med-fev-5", domain: "medical", ja: "熱が続くときは、元気そうでも3日目あたりに一度受診してください。", en: "If the fever lasts, please come in around the third day, even if she seems fine." },
  { id: "med-fev-6", domain: "medical", ja: "熱が下がるまでは、一緒に経過を見せてください。風邪以外の原因も見逃さないためです。", en: "Until the fever comes down, let's follow it together — so we don't miss anything other than a simple cold." },
  { id: "med-fev-7", domain: "medical", ja: "解熱して24時間たって元気なら、登園できます。", en: "She can go back to daycare once she's been fever-free for 24 hours and feels well." },
  { id: "med-fev-8", domain: "medical", ja: "咳だけ長く残るのは、気道が敏感になっているからです。つらいときは炎症をしっかり取ります。", en: "A lingering cough means her airways have become sensitive. When it's hard on her, we treat the inflammation properly." },
  { id: "med-fev-9", domain: "medical", ja: "どうか、ご自分を責めないでください。お父さん・お母さんの体調も大切にしてください。", en: "Please don't blame yourself — and take care of your own health too." },
  { id: "med-fev-10", domain: "medical", ja: "何度風邪をひいても大丈夫。少しずつ、強くなっていきます。", en: "However many colds she catches, she'll be okay. Little by little, she's getting stronger." },
  // 胃腸炎
  { id: "med-gi-1", domain: "medical", ja: "胃腸炎で一番こわいのは脱水です。", en: "With a stomach bug, the thing we worry about most is dehydration." },
  { id: "med-gi-2", domain: "medical", ja: "吐き気が強い間（半日ほど）は、無理に飲ませないでください。", en: "While the nausea is strong — usually about half a day — don't force fluids." },
  { id: "med-gi-3", domain: "medical", ja: "落ち着いてきたら、スプーン一杯を5〜15分おきに、点滴みたいに少しずつ。", en: "Once it settles, give a spoonful every 5 to 15 minutes — like a slow drip." },
  { id: "med-gi-4", domain: "medical", ja: "一気に飲ませると、また吐きやすいので、少しずつ。", en: "If she drinks a lot at once, she'll likely throw up again — so little by little." },
  { id: "med-gi-5", domain: "medical", ja: "水分が取れたら、お粥やうどんなど消化のいいものから。", en: "Once she can keep fluids down, start with easy foods like rice porridge or noodles." },
  { id: "med-gi-6", domain: "medical", ja: "下痢の間は、牛乳や乳製品は控えめに。", en: "Go easy on milk and dairy while she has diarrhea." },
  { id: "med-gi-7", domain: "medical", ja: "数日食べられなくても、水分と塩分・糖分が取れていれば大丈夫です。", en: "Even if she can't eat for a few days, she's fine as long as she's getting fluids, salt, and sugar." },
  { id: "med-gi-8", domain: "medical", ja: "下痢でお尻がかぶれます。赤くなる前にワセリンで守りましょう。", en: "Diarrhea can make her bottom sore — protect it with Vaseline before it turns red." },
  { id: "med-gi-9", domain: "medical", ja: "もし吐いても、焦らなくて大丈夫。少し戻して、また少しずつで大丈夫です。", en: "If she throws up, don't worry — just ease off and start slow again." },
  { id: "med-gi-10", domain: "medical", ja: "ぐったり、目がうつろ、8〜10時間おしっこが出ない——これは夜でも救急へ。", en: "If she's very limp, her eyes look vacant, or she hasn't peed in 8 to 10 hours, go to the ER, even at night." },
  // 便秘
  { id: "med-con-1", domain: "medical", ja: "便が硬いこと＝便秘、とは限りません。大事なのは、すっきり出し切れているかです。", en: "Hard stool doesn't always mean constipation. What matters is whether she can empty out completely." },
  { id: "med-con-2", domain: "medical", ja: "まず、直腸にたまったうんちを、しっかり出し切ることから始めます。", en: "We start by fully emptying the stool that's built up in the rectum." },
  { id: "med-con-3", domain: "medical", ja: "そのために、浣腸を主役に使います。", en: "To do that, we use enemas as the main tool." },
  { id: "med-con-4", domain: "medical", ja: "浣腸は癖になりません。安心してください。", en: "Enemas are not habit-forming — please don't worry about that." },
  { id: "med-con-5", domain: "medical", ja: "浣腸は、その日のうんちを出すためだけのものではありません。", en: "An enema isn't just about passing today's stool." },
  { id: "med-con-6", domain: "medical", ja: "毎日しっかり出すことで、腸のセンサーと押し出す力を取り戻します。", en: "By emptying every day, her bowel gets its sensation and pushing power back." },
  { id: "med-con-7", domain: "medical", ja: "お薬を減らせたら治った、ではありません。毎日すっきり出せる習慣が本当のゴールです。", en: "Cutting back the medicine isn't the goal. The real goal is a daily habit of emptying comfortably." },
  { id: "med-con-8", domain: "medical", ja: "これは長期戦です。焦らず、少しずつ進めましょう。", en: "This is a long game — let's take it step by step, without rushing." },
  { id: "med-con-9", domain: "medical", ja: "硬い便で切れると、痛くて我慢して、もっと便秘になります。その悪循環を断ちます。", en: "When hard stool causes a tear, it hurts, she holds it in, and it gets worse — we break that cycle." },
  { id: "med-con-10", domain: "medical", ja: "今、お子さんがどのステップにいるかを見ながら進めます。", en: "We move forward while checking which step she's at right now." },
  // 発熱ホームケア
  { id: "med-hf-1", domain: "medical", ja: "高い熱だけで、脳がダメになることはありません。", en: "A high fever on its own won't harm her brain." },
  { id: "med-hf-2", domain: "medical", ja: "熱は、体が病原体と戦っている証拠です。", en: "The fever is a sign that her body is fighting off the infection." },
  { id: "med-hf-3", domain: "medical", ja: "解熱剤は病気を治す薬ではなく、つらさを和らげるものです。", en: "Fever medicine doesn't cure the illness — it just eases the discomfort." },
  { id: "med-hf-4", domain: "medical", ja: "何度で使うかより、「つらそうかどうか」で決めてください。", en: "Rather than a set temperature, go by whether she looks miserable." },
  { id: "med-hf-5", domain: "medical", ja: "水分が取れないくらいつらい時、眠れない時に使ってください。", en: "Use it when she's too miserable to drink, or when she can't sleep." },
  { id: "med-hf-6", domain: "medical", ja: "高熱でも元気そうなら、使わなくて大丈夫です。", en: "If she has a high fever but still seems fine, you don't need to give it." },
  { id: "med-hf-7", domain: "medical", ja: "解熱剤は6時間以上あけて、1日3回までです。", en: "Give the fever medicine at least six hours apart, up to three times a day." },
  { id: "med-hf-8", domain: "medical", ja: "坐薬と飲み薬、効き目は同じです。吐く子は坐薬でどうぞ。", en: "Suppository or syrup — they work the same. Use the suppository if she tends to vomit." },
  { id: "med-hf-9", domain: "medical", ja: "生後3ヶ月未満で38度以上の熱は、夜でもすぐ受診してください。", en: "For a baby under three months with a fever over 38°C, please see a doctor right away, even at night." },
  { id: "med-hf-10", domain: "medical", ja: "数字に振り回されず、お子さんの様子を見てあげてください。", en: "Try not to chase the number — watch how she actually looks." },
  // けいれん（応急）
  { id: "med-sz-1", domain: "medical", ja: "けいれんが起きても、まず落ち着いて。大丈夫です。", en: "If she has a seizure, first stay calm — it's going to be okay." },
  { id: "med-sz-2", domain: "medical", ja: "多くは数分で止まります。横に寝かせて、見守ってあげてください。", en: "Most seizures stop within a few minutes. Lay her on her side and just watch over her." },
  { id: "med-sz-3", domain: "medical", ja: "吐いたら、窒息しないよう、体ごと顔を横向きに。", en: "If she vomits, turn her whole body so her face is to the side, so she doesn't choke." },
  { id: "med-sz-4", domain: "medical", ja: "口に何かを入れたり、押さえつけたりは絶対にしないでください。", en: "Never put anything in her mouth, and don't hold her down." },
  { id: "med-sz-5", domain: "medical", ja: "5分以上止まらないときは、救急車を呼んでください。", en: "If it doesn't stop within five minutes, call an ambulance." },
  { id: "med-sz-6", domain: "medical", ja: "初めてのけいれんや、怖いと思ったら、迷わず救急車で大丈夫です。", en: "If it's her first seizure, or you feel scared, don't hesitate to call an ambulance." },
  { id: "med-sz-7", domain: "medical", ja: "けいれんの後、意識が戻らない・反応が鈍いときも、すぐ受診を。", en: "If she doesn't come around or stays unresponsive afterward, get her seen right away." },
  { id: "med-sz-8", domain: "medical", ja: "可能なら、けいれんの長さと様子を覚えておいてください。", en: "If you can, note how long it lasted and what it looked like." },

  // ── 旅行・日常（口語・テンポ重視）──────────────
  // つなぎ言葉（口語のリズムを作る）
  { id: "tr-fill-1", domain: "travel", ja: "（切り出し）で、〜なんですけど。", en: "So, ..." },
  { id: "tr-fill-2", domain: "travel", ja: "へえ、いいですね！", en: "Oh, nice!" },
  { id: "tr-fill-3", domain: "travel", ja: "えーと、そうですね…", en: "Well, let me think..." },
  { id: "tr-fill-4", domain: "travel", ja: "ですよね？（同意をうながす）", en: "You know what I mean?" },
  // 軸（強がらない・深掘り）
  { id: "tr-axis-1", domain: "travel", ja: "ちょっと助けてもらえますか？", en: "Could you help me out real quick?" },
  { id: "tr-axis-2", domain: "travel", ja: "英語まだ勉強中で。少しゆっくり話してもらえますか？", en: "I'm still learning English — could you slow down a little?" },
  { id: "tr-axis-3", domain: "travel", ja: "うまく聞き取れなくて。もう一回いいですか？", en: "Sorry, I didn't quite catch that — could you say it again?" },
  { id: "tr-axis-4", domain: "travel", ja: "念のため、もう一つだけ確認させて。", en: "Just to be sure — one more thing." },
  // 入国審査
  { id: "tr-imm-1", domain: "travel", ja: "観光で来ました。10日くらいです。", en: "I'm here as a tourist, for about ten days." },
  { id: "tr-imm-2", domain: "travel", ja: "家族と一緒です。", en: "I'm with my family." },
  { id: "tr-imm-3", domain: "travel", ja: "日本で子どもの医者をしています。", en: "I'm a children's doctor back in Japan." },
  // ホテル
  { id: "tr-hotel-1", domain: "travel", ja: "チェックインお願いします。小森で予約してます。", en: "Hi, I'd like to check in — it's under Komori." },
  { id: "tr-hotel-2", domain: "travel", ja: "エレベーターでカードキーが反応しないんです。直してもらえますか？", en: "My key card isn't working in the elevator — could you sort it out for me?" },
  { id: "tr-hotel-3", domain: "travel", ja: "朝食って何時からですか？", en: "What time's breakfast?" },
  // 空港
  { id: "tr-air-1", domain: "travel", ja: "この便のゲートはどこですか？", en: "Which gate does this flight leave from?" },
  { id: "tr-air-2", domain: "travel", ja: "乗り継ぎなんですが、間に合いますか？", en: "I've got a connecting flight — will I make it?" },
  // 荷物（深く確認）
  { id: "tr-bag-1", domain: "travel", ja: "荷物は羽田までスルーですか？それともここで受け取り？", en: "Is my bag checked through to Haneda, or do I grab it here?" },
  { id: "tr-bag-2", domain: "travel", ja: "乗り継ぎの間、荷物は勝手に運ばれます？何かやることは？", en: "Does my bag get transferred automatically, or do I need to do anything?" },
  { id: "tr-bag-3", domain: "travel", ja: "もし間に合わなくても、羽田で受け取れますか？", en: "If it doesn't make it, can I still pick it up at Haneda?" },
  // 支払い・買い物・食事
  { id: "tr-pay-1", domain: "travel", ja: "カードで払えますか？", en: "Can I pay by card?" },
  { id: "tr-pay-2", domain: "travel", ja: "おすすめは？", en: "What do you recommend?" },
  { id: "tr-pay-3", domain: "travel", ja: "お会計お願いします。", en: "Can we get the check?" },
  { id: "tr-beer-1", domain: "travel", ja: "ビール何がありますか？軽めのと、しっかりめ、どっちがいい？", en: "What beers do you have? Something light, or something stronger?" },
  { id: "tr-beer-2", domain: "travel", ja: "地元のビールってあります？何が違うんですか？", en: "Got any local beers? What's the difference?" },
  // 旅仲間との雑談
  { id: "tr-chat-1", domain: "travel", ja: "どちらから来たんですか？", en: "So, where are you from?" },
  { id: "tr-chat-2", domain: "travel", ja: "何しに来たんですか？（旅の目的）", en: "What brings you here?" },
  { id: "tr-chat-3", domain: "travel", ja: "へえ、面白い！もっと聞かせて。", en: "Oh nice — tell me more!" },
  { id: "tr-chat-4", domain: "travel", ja: "日本から来ました。子どもの医者で、お腹と栄養が専門です。", en: "I'm from Japan — a kids' doctor, I focus on gut health and nutrition." },
  { id: "tr-chat-5", domain: "travel", ja: "また連絡取れたら。番号交換しません？", en: "Let's keep in touch — want to swap numbers?" },
  { id: "tr-chat-6", domain: "travel", ja: "会えてよかった。良い旅を！", en: "Really nice meeting you — safe travels!" },
  // 聞き取れない時
  { id: "tr-rec-1", domain: "travel", ja: "ごめん、もう一回いい？", en: "Sorry, say that again?" },
  { id: "tr-rec-2", domain: "travel", ja: "つまり、〜ってこと？", en: "So you mean ___, right?" },
  { id: "tr-rec-3", domain: "travel", ja: "それ、どういう意味ですか？", en: "What does that mean?" },
  // 機内（客室乗務員とのやりとり）
  { id: "tr-cabin-1", domain: "travel", ja: "毛布をもらえますか？", en: "Could I get a blanket?" },
  { id: "tr-cabin-2", domain: "travel", ja: "お水をもらえますか？", en: "Could I get some water?" },
  { id: "tr-cabin-3", domain: "travel", ja: "食事はチキンとビーフ、どちらがありますか？", en: "For the meal, do you have chicken or beef?" },
  { id: "tr-cabin-4", domain: "travel", ja: "すみません、通してもらえますか？", en: "Excuse me, could I get through?" },
  { id: "tr-cabin-5", domain: "travel", ja: "席を倒してもいいですか？", en: "Is it okay if I recline my seat?" },
  { id: "tr-cabin-6", domain: "travel", ja: "入国カードをもう一枚もらえますか？", en: "Could I get another arrival card?" },
  // ショップ（買い物）
  { id: "tr-shop-1", domain: "travel", ja: "これ、試着できますか？", en: "Can I try this on?" },
  { id: "tr-shop-2", domain: "travel", ja: "もう少し大きいサイズはありますか？", en: "Do you have this in a bigger size?" },
  { id: "tr-shop-3", domain: "travel", ja: "これ、いくらですか？", en: "How much is this?" },
  { id: "tr-shop-4", domain: "travel", ja: "見ているだけです、ありがとう。", en: "I'm just looking, thanks." },
  { id: "tr-shop-5", domain: "travel", ja: "別の色はありますか？", en: "Do you have this in another color?" },
  { id: "tr-shop-6", domain: "travel", ja: "プレゼント用に包んでもらえますか？", en: "Could you gift-wrap this for me?" },
  // 道・移動・タクシー
  { id: "tr-way-1", domain: "travel", ja: "駅はどっちですか？", en: "Which way is the station?" },
  { id: "tr-way-2", domain: "travel", ja: "（タクシーで）この住所までお願いします。", en: "Could you take me to this address?" },
  { id: "tr-way-3", domain: "travel", ja: "ここで停めてください。", en: "You can stop here, please." },
  // 体調不良を伝える（旅先）
  { id: "tr-sick-1", domain: "travel", ja: "気分が悪いんです。", en: "I'm not feeling well." },
  { id: "tr-sick-2", domain: "travel", ja: "頭が痛いです。", en: "I have a headache." },
  { id: "tr-sick-3", domain: "travel", ja: "お腹を壊しました。", en: "I have an upset stomach." },
  { id: "tr-sick-4", domain: "travel", ja: "子どもが熱があります。", en: "My child has a fever." },
  { id: "tr-sick-5", domain: "travel", ja: "近くに病院か薬局はありますか？", en: "Is there a hospital or a pharmacy nearby?" },
  { id: "tr-sick-6", domain: "travel", ja: "ナッツのアレルギーがあります。", en: "I have a nut allergy." },
  // 薬局
  { id: "tr-pharm-1", domain: "travel", ja: "頭痛に効くものはありますか？", en: "Do you have anything for a headache?" },
  { id: "tr-pharm-2", domain: "travel", ja: "子ども用の解熱剤はありますか？", en: "Do you have fever medicine for kids?" },
  { id: "tr-pharm-3", domain: "travel", ja: "これは1日何回飲みますか？", en: "How many times a day do I take this?" },
  // トラブル（紛失・遅延）
  { id: "tr-trb-1", domain: "travel", ja: "荷物が出てこないんです。", en: "My bag hasn't come out." },
  { id: "tr-trb-2", domain: "travel", ja: "財布をなくしました。", en: "I've lost my wallet." },
  { id: "tr-trb-3", domain: "travel", ja: "飛行機が遅れています。どうすればいいですか？", en: "My flight is delayed — what should I do?" },
  { id: "tr-trb-4", domain: "travel", ja: "助けてください。", en: "I need some help." },
  // 交通（電車・バス・地下鉄）
  { id: "tr-trn-1", domain: "travel", ja: "この電車、〜に行きますか？", en: "Does this train go to ___?" },
  { id: "tr-trn-2", domain: "travel", ja: "切符はどこで買えますか？", en: "Where can I buy a ticket?" },
  { id: "tr-trn-3", domain: "travel", ja: "〜へは、何番線ですか？", en: "Which platform is it for ___?" },
  { id: "tr-trn-4", domain: "travel", ja: "次のバスは何時ですか？", en: "What time's the next bus?" },
  { id: "tr-trn-5", domain: "travel", ja: "〜で降りたいんです。着いたら教えてもらえますか？", en: "I want to get off at ___ — could you let me know when we're there?" },
  // 観光・チケット・写真
  { id: "tr-sight-1", domain: "travel", ja: "大人2枚、子ども1枚ください。", en: "Two adults and one child, please." },
  { id: "tr-sight-2", domain: "travel", ja: "何時まで開いていますか？", en: "How late are you open?" },
  { id: "tr-sight-3", domain: "travel", ja: "中で写真を撮ってもいいですか？", en: "Is it okay to take photos inside?" },
  { id: "tr-sight-4", domain: "travel", ja: "写真を撮ってもらえますか？", en: "Could you take a photo of us?" },
  // お金・両替・チップ
  { id: "tr-money-1", domain: "travel", ja: "これを両替できますか？", en: "Can I exchange this?" },
  { id: "tr-money-2", domain: "travel", ja: "近くにATMはありますか？", en: "Is there an ATM nearby?" },
  { id: "tr-money-3", domain: "travel", ja: "チップは必要ですか？", en: "Do I need to leave a tip?" },
  // レストラン（予約・詳細）
  { id: "tr-rest-1", domain: "travel", ja: "今夜、2名で予約できますか？", en: "Can I book a table for two tonight?" },
  { id: "tr-rest-2", domain: "travel", ja: "窓際の席はありますか？", en: "Could we get a table by the window?" },
  { id: "tr-rest-3", domain: "travel", ja: "これ、ナッツは入っていますか？", en: "Does this have any nuts in it?" },
  { id: "tr-rest-4", domain: "travel", ja: "取り分け用の小皿をもらえますか？", en: "Could we get some small plates to share?" },
  { id: "tr-rest-5", domain: "travel", ja: "これ、持ち帰りできますか？", en: "Can I get this to go?" },
  // カフェ・Wi-Fi
  { id: "tr-cafe-1", domain: "travel", ja: "Wi-Fiは使えますか？パスワードは？", en: "Do you have Wi-Fi? What's the password?" },
  { id: "tr-cafe-2", domain: "travel", ja: "ここ、少し座ってもいいですか？", en: "Is it okay if I sit here for a bit?" },
  // 緊急・紛失
  { id: "tr-emg-1", domain: "travel", ja: "警察を呼んでもらえますか？", en: "Could you call the police?" },
  { id: "tr-emg-2", domain: "travel", ja: "日本大使館はどこですか？", en: "Where is the Japanese embassy?" },
  // 雑談・つかみ
  { id: "tr-sm-1", domain: "travel", ja: "今日はいい天気ですね。", en: "Lovely weather today, isn't it?" },
  { id: "tr-sm-2", domain: "travel", ja: "このあたりで、おすすめの場所はありますか？", en: "Any spots around here you'd recommend?" },
  { id: "tr-sm-3", domain: "travel", ja: "写真、撮りましょうか？", en: "Want me to take a photo for you?" },
  // 言い回しのバリエーション（同じ意図・別の言い方）
  { id: "tr-var-1", domain: "travel", ja: "（お会計・別の言い方）お勘定お願いします。", en: "Just the bill, please." },
  { id: "tr-var-2", domain: "travel", ja: "（ありがとう・くだけて）ほんと助かりました！", en: "Thanks so much — you're a lifesaver!" },
  { id: "tr-var-3", domain: "travel", ja: "（ごめん・軽く）あ、すみません！", en: "Oh, sorry about that!" },
  { id: "tr-var-4", domain: "travel", ja: "（もう一回・くだけて）ごめん、なんて言った？", en: "Sorry, what was that?" }
];
