/* Hanaseru 辞書データ（Vault 20_診療英語 / 21_旅行日常 から抽出）
   1カード = { id, domain, ja, en, note }
   domain: sign(署名フレーズ) / medical(診療) / travel(旅行・日常)
   ※ 辞書を育てたら、この配列に足す（または Vault からの変換で再生成）。 */
window.HANASERU_CARDS = [
  // ── 署名フレーズ（辞書の背骨・軸）────────────────
  { id: "sign-01", domain: "sign", ja: "ご心配ですよね。お気持ちわかります。", en: "You must be worried. I understand." },
  { id: "sign-02", domain: "sign", ja: "まず、安心してください。", en: "First, please don't worry." },
  { id: "sign-03", domain: "sign", ja: "これは子どもによくあることです。", en: "This is very common in children." },
  { id: "sign-04", domain: "sign", ja: "本当の◯◯ではありません。むしろ△△です。", en: "It isn't really ___. It's more like ___." },
  { id: "sign-05", domain: "sign", ja: "一番大事なのは、〜です。", en: "The main thing is ___." },
  { id: "sign-06", domain: "sign", ja: "その都度、しっかり治していきましょう。", en: "Let's treat it properly each time." },
  { id: "sign-07", domain: "sign", ja: "一緒に様子を見ていきましょう。", en: "Let's watch how she does. We'll do it together." },
  { id: "sign-08", domain: "sign", ja: "ですから、心配いりません。", en: "So, please don't worry." },
  { id: "sign-09", domain: "sign", ja: "何かあれば、いつでも来てください。", en: "If anything happens, please come back anytime." },
  { id: "sign-10", domain: "sign", ja: "焦らず、少しずつ良くしていきましょう。", en: "No rush. Let's get her better step by step." },

  // ── 診療英語 ───────────────────────────────
  { id: "med-intro-1", domain: "medical", ja: "私は小児外科医です。子どものお腹と栄養を診ています。", en: "I'm a pediatric surgeon. I take care of children's tummy problems and nutrition." },
  { id: "med-intro-2", domain: "medical", ja: "今日はお子さんの状態を説明して、一緒に方針を決めましょう。", en: "Today, I'll explain how she is doing. Then we'll decide the plan together." },
  { id: "med-ast-1", domain: "medical", ja: "熱と咳、ゼーゼーが続いて、ご心配ですよね。", en: "She has had fever, cough, and wheezing. You must be worried." },
  { id: "med-ast-2", domain: "medical", ja: "まず安心してください。RSウイルスの検査は陰性でした。", en: "First, please don't worry. Her RSV test was negative." },
  { id: "med-ast-3", domain: "medical", ja: "子どもは風邪をひくと、気道が敏感になってゼーゼーします。", en: "When children get a cold, their airways get sensitive. So they wheeze." },
  { id: "med-ast-4", domain: "medical", ja: "喘息のようなゼーゼーですが、ほとんどの場合、本当の喘息ではありません。", en: "It sounds like asthma. But in most cases, it is not true asthma.", note: "「ほとんどは本当の喘息ではない」を一言で言うときのカード。in most cases で『ほとんどは』を必ず入れる。" },
  { id: "med-ast-5", domain: "medical", ja: "酸素の値は問題ありません。ただ、ゼーゼーで夜眠りにくくなります。", en: "Her oxygen level is fine. But the wheezing can make it hard to sleep at night." },
  { id: "med-ast-6", domain: "medical", ja: "クリニックで吸入をしました。気道を広げて楽にする薬です。", en: "We did a nebulizer treatment here. It opens the airways. It makes breathing easier." },
  { id: "med-ast-7", domain: "medical", ja: "長く続く治療は要りません。風邪のたびにしっかり治すことが大事です。", en: "She doesn't need long-term treatment. But each time she gets a cold, we treat it well." },
  { id: "med-ast-8", domain: "medical", ja: "今すぐ「喘息」と決めつける必要はありません。", en: "We don't need to call this asthma right now." },
  { id: "med-ast-9", domain: "medical", ja: "大事なのは診断名より、今の気道の炎症をしっかり取ることです。", en: "The name is not important now. The important thing is to treat the inflammation in her airways." },
  { id: "med-ast-10", domain: "medical", ja: "炎症をしっかり取ってリセットすると、本人も楽になり、次のゼーゼーの予防にもなります。", en: "Once we clear the inflammation, her airways get a reset. She feels better. And it helps prevent the next wheezing." },
  { id: "med-ast-11", domain: "medical", ja: "目標はシンプルです。夜ぐっすり眠れて、楽に呼吸できること。", en: "The goal is simple. She sleeps well at night. She breathes easily." },
  // 「ゼーゼー＝喘息？」の説明の流れ（院長 2026-09-27：一過性で、ほとんどは成長とともに治る。ごく一部だけ本当の喘息）
  { id: "med-ast-12", domain: "medical", ja: "小さな子は、風邪をひくとすぐにゼーゼーしやすいんです。", en: "Small children often wheeze as soon as they get a cold." },
  { id: "med-ast-13", domain: "medical", ja: "この子も、風邪のたびにゼーゼーしていますね。", en: "She wheezes every time she catches a cold, doesn't she?", note: "文の最後の doesn't she? で『〜ですよね』と相手にうなずいてもらう。" },
  { id: "med-ast-14", domain: "medical", ja: "ゼーゼーが3回以上あって、気管支を広げる吸入で治まる場合は、いったん「小児喘息」と呼びます。", en: "If she wheezes three or more times, and it gets better with a nebulizer treatment, we call it childhood asthma for now.", note: "for now（いったん・今のところ）が『暫定的な』の王道の言い方。provisional は医師同士の言葉。" },
  { id: "med-ast-15", domain: "medical", ja: "でも、ほとんどは一時的なもので、本当の喘息になる子はごくわずかです。", en: "But in most cases, it is temporary. Very few children get true asthma.", note: "go on to ～＝その後〜になる。" },
  { id: "med-ast-16", domain: "medical", ja: "その都度、風邪の治療と、敏感になった気道の治療をしっかり行います。", en: "Each time, we treat the cold. And we treat the sensitive airways." },
  { id: "med-ast-17", domain: "medical", ja: "炎症をしっかり取っていけば、ほとんどの子は大きくなるにつれて治っていきます。", en: "If we clear the inflammation each time, most children grow out of it.", note: "grow out of it＝成長とともに（症状から）卒業する。保護者にいちばん伝わる言い方。" },
  { id: "med-ast-18", domain: "medical", ja: "ごく一部の子だけが、本当の喘息として長く治療が必要になります。", en: "Only a few children have true asthma. They need long-term treatment." },
  { id: "med-med-1", domain: "medical", ja: "今の風邪薬は続けてください。今日、追加でお出しします。", en: "Please keep giving the current cold medicine. I'll give you more today." },
  { id: "med-med-2", domain: "medical", ja: "熱が数日続いて、中耳炎と軽い気管支炎が出ています。", en: "She has had a fever for a few days. Now she has an ear infection and mild bronchitis." },
  { id: "med-med-3", domain: "medical", ja: "なので抗生物質を新しく足します。両方きちんと飲ませてください。", en: "So, I'll add an antibiotic. Please give her both medicines." },
  { id: "med-med-4", domain: "medical", ja: "まずは熱が下がるか、鼻や胸の症状が良くなるかを見ていきましょう。", en: "First, let's see if the fever comes down. And let's see if her nose and chest get better." },
  { id: "med-rev-1", domain: "medical", ja: "熱が下がらなければ、木曜か金曜にまた来てください。", en: "If the fever doesn't come down, please come back on Thursday or Friday." },
  { id: "med-rev-2", domain: "medical", ja: "夜の咳がひどい時は、診療時間内なら予約なしで吸入に来られます。この特急券をどうぞ。", en: "If her cough is bad at night, you can come for a nebulizer treatment. No appointment needed, during clinic hours. Here is an express ticket." },
  { id: "med-rev-3", domain: "medical", ja: "これだけは救急へ：横になって全く眠れない。", en: "Please go to the ER for these signs. She can't sleep at all lying down." },
  { id: "med-rev-4", domain: "medical", ja: "肩やお腹を使って息をしている。目がうつろ。", en: "She is using her shoulders or belly to breathe. Or her eyes look dazed." },
  { id: "med-fev-1", domain: "medical", ja: "集団生活を始めた子が、毎週のように風邪をひくのは、異常ではありません。", en: "A child who just started daycare gets a cold almost every week. This is normal." },
  { id: "med-fev-2", domain: "medical", ja: "今は、体が初めてのウイルスに出会って、免疫を一つずつ学んでいる最中です。", en: "Right now, her body is meeting new viruses for the first time. It's building immunity one by one." },
  { id: "med-fev-3", domain: "medical", ja: "3ヶ月から半年ほどで、少しずつ強くなって山を越えます。", en: "Over three to six months, she gets stronger little by little. Then it gets easier." },
  { id: "med-fev-4", domain: "medical", ja: "完治を狙わなくて大丈夫。つらい症状を楽にしながら、根気よく付き合いましょう。", en: "We don't need a perfect cure. Let's ease the hard symptoms. And let's be patient together." },
  { id: "med-fev-5", domain: "medical", ja: "熱が続くときは、元気そうでも3日目あたりに一度受診してください。", en: "If the fever continues, please come in around day three. Even if she seems fine." },
  { id: "med-fev-6", domain: "medical", ja: "熱が下がるまでは、一緒に経過を見せてください。風邪以外の原因も見逃さないためです。", en: "Until the fever comes down, please keep coming in. That way we don't miss anything other than a cold." },
  { id: "med-fev-7", domain: "medical", ja: "解熱して24時間たって元気なら、登園できます。", en: "She can go back to daycare once she's been fever-free for 24 hours and feels well." },
  { id: "med-fev-8", domain: "medical", ja: "咳だけ長く残るのは、気道が敏感になっているからです。つらいときは炎症をしっかり取ります。", en: "A cough can stay for a while. That's because her airways are sensitive. If it's hard on her, we treat the inflammation." },
  { id: "med-fev-9", domain: "medical", ja: "どうか、ご自分を責めないでください。お父さん・お母さんの体調も大切にしてください。", en: "Please don't blame yourself. And please take care of your own health too." },
  { id: "med-fev-10", domain: "medical", ja: "何度風邪をひいても大丈夫。少しずつ、強くなっていきます。", en: "It's okay if she gets many colds. Little by little, she is getting stronger." },
  // 胃腸炎
  { id: "med-gi-1", domain: "medical", ja: "胃腸炎で一番こわいのは脱水です。", en: "With a stomach bug, the biggest worry is dehydration." },
  { id: "med-gi-2", domain: "medical", ja: "吐き気が強い間（半日ほど）は、無理に飲ませないでください。", en: "While the nausea is strong, for about half a day, don't force her to drink." },
  { id: "med-gi-3", domain: "medical", ja: "落ち着いてきたら、スプーン一杯を5〜15分おきに、点滴みたいに少しずつ。", en: "When it settles, give one spoonful every 5 to 15 minutes. Slowly, like a drip." },
  { id: "med-gi-4", domain: "medical", ja: "一気に飲ませると、また吐きやすいので、少しずつ。", en: "If she drinks a lot at once, she will throw up again. So, little by little." },
  { id: "med-gi-5", domain: "medical", ja: "水分が取れたら、お粥やうどんなど消化のいいものから。", en: "When she can keep fluids down, start with easy foods. Rice porridge or noodles are good." },
  { id: "med-gi-6", domain: "medical", ja: "下痢の間は、牛乳や乳製品は控えめに。", en: "Give less milk and dairy while she has diarrhea." },
  { id: "med-gi-7", domain: "medical", ja: "数日食べられなくても、水分と塩分・糖分が取れていれば大丈夫です。", en: "Even if she can't eat for a few days, that's okay. She just needs fluids, salt, and sugar." },
  { id: "med-gi-8", domain: "medical", ja: "下痢でお尻がかぶれます。赤くなる前にワセリンで守りましょう。", en: "Diarrhea can make her bottom sore. Put Vaseline on it before it turns red." },
  { id: "med-gi-9", domain: "medical", ja: "もし吐いても、焦らなくて大丈夫。少し戻して、また少しずつで大丈夫です。", en: "If she throws up, don't worry. Take a short break. Then start again, little by little." },
  { id: "med-gi-10", domain: "medical", ja: "ぐったり、目がうつろ、8〜10時間おしっこが出ない——これは夜でも救急へ。", en: "If she is very limp, her eyes look empty, or no pee for 8 to 10 hours, go to the ER. Even at night." },
  // 便秘
  { id: "med-con-1", domain: "medical", ja: "便が硬いこと＝便秘、とは限りません。大事なのは、すっきり出し切れているかです。", en: "Hard stool does not always mean constipation. The important thing is, can she empty out completely?" },
  { id: "med-con-2", domain: "medical", ja: "まず、直腸にたまったうんちを、しっかり出し切ることから始めます。", en: "First, we empty the stool that has built up in the rectum." },
  { id: "med-con-3", domain: "medical", ja: "直腸を出し切るために、浣腸を主役に使います。", en: "To empty the rectum, an enema is our main tool." },
  { id: "med-con-4", domain: "medical", ja: "浣腸は癖になりません。安心してください。", en: "Enemas are not habit-forming. Please don't worry." },
  { id: "med-con-5", domain: "medical", ja: "浣腸は、その日のうんちを出すためだけのものではありません。", en: "An enema is not just for passing today's stool." },
  { id: "med-con-6", domain: "medical", ja: "毎日しっかり出すことで、腸のセンサーと押し出す力を取り戻します。", en: "By emptying every day, her bowel gets back its sensation and its pushing power." },
  { id: "med-con-7", domain: "medical", ja: "お薬を減らせたら治った、ではありません。毎日すっきり出せる習慣が本当のゴールです。", en: "Less medicine does not mean she is cured. The real goal is emptying comfortably every day." },
  { id: "med-con-8", domain: "medical", ja: "これは長期戦です。焦らず、少しずつ進めましょう。", en: "This takes a long time. No rush. Let's go step by step." },
  { id: "med-con-9", domain: "medical", ja: "硬い便で切れると、痛くて我慢して、もっと便秘になります。その悪循環を断ちます。", en: "Hard stool can cause a tear. It hurts, so she holds it in. Then it gets worse. We break that cycle." },
  { id: "med-con-10", domain: "medical", ja: "今、お子さんがどのステップにいるかを見ながら進めます。", en: "We check which step she is at now. Then we move forward." },
  // 発熱ホームケア
  { id: "med-hf-1", domain: "medical", ja: "高い熱だけで、脳がダメになることはありません。", en: "A high fever alone won't damage her brain." },
  { id: "med-hf-2", domain: "medical", ja: "熱は、体が病原体と戦っている証拠です。", en: "The fever is a sign that her body is fighting the infection." },
  { id: "med-hf-3", domain: "medical", ja: "解熱剤は病気を治す薬ではなく、つらさを和らげるものです。", en: "Fever medicine doesn't cure the illness. It just makes her more comfortable." },
  { id: "med-hf-4", domain: "medical", ja: "何度で使うかより、「つらそうかどうか」で決めてください。", en: "Don't go by the number. Go by how she looks." },
  { id: "med-hf-5", domain: "medical", ja: "水分が取れないくらいつらい時、眠れない時に使ってください。", en: "Use it when she is too uncomfortable to drink. Or when she can't sleep." },
  { id: "med-hf-6", domain: "medical", ja: "高熱でも元気そうなら、使わなくて大丈夫です。", en: "If she has a high fever but seems fine, you don't need to give it." },
  { id: "med-hf-7", domain: "medical", ja: "解熱剤は6時間以上あけて、1日3回までです。", en: "Give the fever medicine at least six hours apart, up to three times a day." },
  { id: "med-hf-8", domain: "medical", ja: "坐薬と飲み薬、効き目は同じです。吐く子は坐薬でどうぞ。", en: "The suppository and the oral medicine work the same. If she vomits, use the suppository." },
  { id: "med-hf-9", domain: "medical", ja: "生後3ヶ月未満で38度以上の熱は、夜でもすぐ受診してください。", en: "A baby under three months with a fever of 38°C or higher must see a doctor right away. Even at night." },
  { id: "med-hf-10", domain: "medical", ja: "数字に振り回されず、お子さんの様子を見てあげてください。", en: "Don't worry too much about the number. Look at how she is doing." },
  // けいれん（応急）
  { id: "med-sz-1", domain: "medical", ja: "けいれんが起きても、まず落ち着いて。大丈夫です。", en: "If she has a seizure, first stay calm. It will be okay." },
  { id: "med-sz-2", domain: "medical", ja: "多くは数分で止まります。安全な場所で横向きに寝かせて、見守ってあげてください。", en: "Most seizures stop in a few minutes. Lay her on her side in a safe place. Then just watch her." },
  { id: "med-sz-3", domain: "medical", ja: "吐いたら、窒息しないよう、体ごと顔を横向きに。", en: "If she vomits, turn her whole body to the side. So she doesn't choke." },
  { id: "med-sz-4", domain: "medical", ja: "口に何かを入れたり、押さえつけたりは絶対にしないでください。", en: "Never put anything in her mouth, and don't hold her down." },
  { id: "med-sz-5", domain: "medical", ja: "5分以上止まらないときは、救急車を呼んでください。", en: "If it doesn't stop in five minutes, call an ambulance." },
  { id: "med-sz-6", domain: "medical", ja: "初めてのけいれんや、怖いと思ったら、迷わず救急車で大丈夫です。", en: "If it's her first seizure, or you feel scared, just call an ambulance. That's fine." },
  { id: "med-sz-7", domain: "medical", ja: "けいれんが止まっても、意識が戻らない・反応が鈍いときは、救急車を呼んでください。", en: "After it stops, if she doesn't wake up, or doesn't respond well, call an ambulance." },
  { id: "med-sz-8", domain: "medical", ja: "可能なら、けいれんの長さと様子を覚えておいてください。", en: "If you can, remember how long it lasted and what it looked like." },
  // 診察室のワンシーン ①子どもへの声かけ（やさしく）
  { id: "med-exam-1", domain: "medical", ja: "（子へ）これから、お体を診させてね。", en: "Let me take a look at you, okay?" },
  { id: "med-exam-2", domain: "medical", ja: "（子へ）もしもし、させてね。ちょっと冷たいよ。", en: "Let me listen to your chest. It might feel a little cold." },
  { id: "med-exam-3", domain: "medical", ja: "（子へ）大きく息を吸って。はい、吐いて。", en: "Take a big breath in. And out." },
  { id: "med-exam-4", domain: "medical", ja: "（子へ）お口を開けて、あーん。", en: "Open wide and say 'ahh.'" },
  { id: "med-exam-5", domain: "medical", ja: "（子へ）お喉を見せてね。上手だね！", en: "Let me see your throat. Good job!" },
  { id: "med-exam-6", domain: "medical", ja: "（子へ）今度はお耳を見るね。じっとしててね。", en: "Now let me look in your ears. Hold still." },
  { id: "med-exam-7", domain: "medical", ja: "（子へ）はい、おしまい！よく頑張ったね。", en: "All done! You did great." },
  // 診察室のワンシーン ②お父さんへの説明（安心できるように）
  { id: "med-exp-1", domain: "medical", ja: "（親へ）肺の音はきれいです。問題ありません。", en: "Her lungs sound clear. No problem there." },
  { id: "med-exp-2", domain: "medical", ja: "（親へ）耳も見ましたが、中耳炎はありません。", en: "I checked her ears too. There is no ear infection." },
  { id: "med-exp-3", domain: "medical", ja: "（親へ）診断は、いわゆる風邪です。", en: "The diagnosis is a common cold." },
  { id: "med-exp-4", domain: "medical", ja: "（親へ）風邪のお薬を出しておきますね。", en: "I'll give you some cold medicine." },
  { id: "med-exp-5", domain: "medical", ja: "（親へ）心配はいりませんよ。", en: "Please don't worry." },
  { id: "med-exp-6", domain: "medical", ja: "（親へ）保育園も、行って大丈夫です。", en: "And she can go to daycare." },
  // 診察室のワンシーン ③鼻の抗原検査（インフル・コロナ）— 子どもへの声かけ（院長 2026-09-27）
  { id: "med-swab-1", domain: "medical", ja: "（子へ）今から、お鼻の検査をするね。", en: "Now I'm going to do a quick test in your nose, okay?" },
  { id: "med-swab-2", domain: "medical", ja: "（子へ）お口で、ゆっくり息をしてね。", en: "Breathe slowly through your mouth." },
  { id: "med-swab-3", domain: "medical", ja: "（子へ）力を抜いて、リラックスしてね。", en: "Just relax your body." },
  { id: "med-swab-4", domain: "medical", ja: "（子へ）細い綿棒が、ゆっくり入るよ。", en: "A thin swab is going in slowly.", note: "swab＝綿棒（スワブ）。検査の綿棒はこの語。" },
  { id: "med-swab-5", domain: "medical", ja: "（子へ）頭を動かさないでね。", en: "Keep your head still for me.", note: "for me を付けると『お願いね』のやさしさが出る。" },
  { id: "med-swab-6", domain: "medical", ja: "（子へ）ちょっとムズムズするけど、すぐ終わるよ。", en: "It might tickle a little, but it'll be over soon.", note: "tickle＝くすぐったい・ムズムズする。hurt（痛い）と言わないのがコツ。" },
  { id: "med-swab-7", domain: "medical", ja: "（子へ）はい、おしまい！よく頑張ったね。", en: "All done! You were so brave." },
  // ③ 親への説明
  { id: "med-flu-1", domain: "medical", ja: "（親へ）今、インフルエンザやコロナがはやっているので、鼻から抗原検査をします。", en: "Flu and COVID are going around now. So we'll do a quick test with a nose swab.", note: "going around＝（病気が）はやっている。日常会話でも一番使う言い方。" },
  { id: "med-flu-2", domain: "medical", ja: "（親へ）全身の状態も、呼吸も問題ありません。", en: "Her overall condition is fine. Her breathing is fine too." },
  { id: "med-flu-3", domain: "medical", ja: "（親へ）ただ、熱が続いているのと、流行もあるので、念のため検査しておきましょう。", en: "But the fever has continued, and these are going around. So let's test, just to be safe.", note: "just to be safe＝念のため。" },
  { id: "med-flu-4", domain: "medical", ja: "（親へ）インフルエンザが陽性なら、抗インフルエンザ薬を出します。", en: "If the flu test is positive, I'll prescribe anti-flu medicine.", note: "antiviral＝抗ウイルス薬（アンタイヴァイラル）。" },
  { id: "med-flu-5", domain: "medical", ja: "（親へ）風邪の症状には風邪薬、熱には解熱剤を出しておきます。", en: "I'll also give cold medicine for her symptoms, and fever medicine for the fever.", note: "解熱剤は fever medicine / fever reducer でも可。bring down the fever＝熱を下げる。" },
  { id: "med-flu-6", domain: "medical", ja: "（親へ）熱が下がれば、心配いりません。", en: "Once the fever comes down, you don't need to worry." },
  { id: "med-flu-7", domain: "medical", ja: "（親へ）おうちで、しっかり良くなるまで様子を見てください。", en: "Please rest at home until she is fully better." },
  { id: "med-flu-8", domain: "medical", ja: "（親へ）登園・登校は、園や学校の基準に従えば大丈夫です。", en: "For daycare or school, please follow their rules.", note: "日本の基準（学校保健安全法）：インフル＝発症後5日かつ解熱後2日（幼児は3日）。コロナ＝発症後5日かつ症状が軽くなって1日。聞かれたら数字で答える。" },
  { id: "med-flu-9", domain: "medical", ja: "（親へ）熱が下がらない、ぐったりしている、息が苦しそうなときは、また受診してください。", en: "Please come back if the fever doesn't come down, she is very weak, or she has trouble breathing.", note: "ぐったり＝very weak / unusually sleepy（英国の小児科では floppy も使う）。" },

  // ── 旅行・日常（口語・テンポ重視）──────────────
  // つなぎ言葉（口語のリズムを作る）
  { id: "tr-fill-1", domain: "travel", ja: "（切り出し）で、〜なんですけど。", en: "So, ..." },
  { id: "tr-fill-2", domain: "travel", ja: "へえ、いいですね！", en: "Oh, nice!" },
  { id: "tr-fill-3", domain: "travel", ja: "えーと、そうですね…", en: "Well, let me think..." },
  { id: "tr-fill-4", domain: "travel", ja: "ですよね？（同意をうながす）", en: "..., right?" },
  // 軸（強がらない・深掘り）
  { id: "tr-axis-1", domain: "travel", ja: "ちょっと助けてもらえますか？", en: "Could you help me for a moment?" },
  { id: "tr-axis-2", domain: "travel", ja: "英語まだ勉強中で。少しゆっくり話してもらえますか？", en: "I'm still learning English — could you slow down a little?" },
  { id: "tr-axis-3", domain: "travel", ja: "うまく聞き取れなくて。もう一回いいですか？", en: "Sorry, I didn't quite catch that — could you say it again?" },
  { id: "tr-axis-4", domain: "travel", ja: "念のため、もう一つだけ確認させて。", en: "Just to be sure — one more thing." },
  // 入国審査
  { id: "tr-imm-1", domain: "travel", ja: "観光で来ました。10日くらいです。", en: "I'm here as a tourist, for about ten days." },
  { id: "tr-imm-2", domain: "travel", ja: "家族と一緒です。", en: "I'm with my family." },
  { id: "tr-imm-3", domain: "travel", ja: "日本で子どもの医者をしています。", en: "I'm a children's doctor back in Japan." },
  // 入国審査 — 聞かれること（まず聞き取れるように）と、王道の答え
  { id: "tr-imm-q1", domain: "travel", ja: "（係官）パスポートを見せてください。", en: "May I see your passport, please?" },
  { id: "tr-imm-q2", domain: "travel", ja: "（係官）渡航の目的は何ですか？", en: "What's the purpose of your visit?" },
  { id: "tr-imm-q3", domain: "travel", ja: "（係官）どのくらい滞在しますか？", en: "How long are you staying?" },
  { id: "tr-imm-q4", domain: "travel", ja: "（係官）どこに泊まりますか？", en: "Where are you staying?" },
  { id: "tr-imm-q5", domain: "travel", ja: "（係官）お仕事は何ですか？", en: "What do you do for a living?" },
  { id: "tr-imm-q6", domain: "travel", ja: "（係官）帰りの航空券はありますか？", en: "Do you have a return ticket?" },
  { id: "tr-imm-4", domain: "travel", ja: "家族旅行です。1週間ほど滞在します。", en: "I'm here on vacation with my family, for about a week." },
  { id: "tr-imm-5", domain: "travel", ja: "〜の近くのホテルに泊まります。これが予約です。", en: "We're staying at a hotel near ___. Here's the booking." },
  { id: "tr-imm-6", domain: "travel", ja: "小児科医です。東京で子どものクリニックをしています。", en: "I'm a pediatrician. I run a children's clinic in Tokyo." },
  { id: "tr-imm-7", domain: "travel", ja: "はい、これが帰りの便です。", en: "Yes, here's my return flight." },
  { id: "tr-imm-8", domain: "travel", ja: "いいえ、2回目です。", en: "No, this is my second time." },
  // 税関
  { id: "tr-cus-q1", domain: "travel", ja: "（係官）申告するものはありますか？", en: "Do you have anything to declare?" },
  { id: "tr-cus-q2", domain: "travel", ja: "（係官）食べ物や植物、肉類はお持ちですか？", en: "Are you carrying any food, plants, or meat?" },
  { id: "tr-cus-q3", domain: "travel", ja: "（係官）バッグを開けてもらえますか？", en: "Could you open your bag, please?" },
  { id: "tr-cus-1", domain: "travel", ja: "いいえ、申告するものはありません。", en: "No, nothing to declare." },
  { id: "tr-cus-2", domain: "travel", ja: "お菓子だけです。未開封です。", en: "Just some snacks — they're still sealed." },
  { id: "tr-cus-3", domain: "travel", ja: "はい、どうぞ。", en: "Sure, go ahead." },
  { id: "tr-cus-4", domain: "travel", ja: "子どもの薬です。処方箋もあります。", en: "It's medicine for my child. I have the prescription." },
  { id: "tr-cus-5", domain: "travel", ja: "友人へのお土産です。", en: "They're gifts for friends." },
  // ホテル
  { id: "tr-hotel-1", domain: "travel", ja: "チェックインお願いします。小森で予約してます。", en: "Hi, I'd like to check in — it's under Komori." },
  { id: "tr-hotel-2", domain: "travel", ja: "エレベーターでカードキーが反応しないんです。直してもらえますか？", en: "My key card isn't working in the elevator — could you sort it out for me?" },
  { id: "tr-hotel-3", domain: "travel", ja: "朝食って何時からですか？", en: "What time's breakfast?" },
  // ホテルのチェックイン — フロントに言われること／こちらから聞くこと
  { id: "tr-hotel-q1", domain: "travel", ja: "（フロント）ご予約はありますか？", en: "Do you have a reservation?" },
  { id: "tr-hotel-q2", domain: "travel", ja: "（フロント）パスポートと、追加料金用のクレジットカードをお願いします。", en: "Could I see your passport and a credit card for incidentals?" },
  { id: "tr-hotel-q3", domain: "travel", ja: "（フロント）お部屋は5階の512号室です。", en: "You're in room 512, on the fifth floor." },
  { id: "tr-hotel-4", domain: "travel", ja: "朝食は付いていますか？", en: "Is breakfast included?" },
  { id: "tr-hotel-5", domain: "travel", ja: "チェックアウトは何時ですか？", en: "What time is checkout?" },
  { id: "tr-hotel-6", domain: "travel", ja: "早めにチェックインできますか？", en: "Is it possible to check in early?" },
  { id: "tr-hotel-7", domain: "travel", ja: "チェックインまで荷物を預かってもらえますか？", en: "Could you hold our bags until check-in?" },
  { id: "tr-hotel-8", domain: "travel", ja: "エレベーターから離れた静かな部屋にできますか？", en: "Could we have a quiet room, away from the elevator?" },
  { id: "tr-hotel-9", domain: "travel", ja: "レイトチェックアウトはできますか？", en: "Could we get a late checkout?" },
  // 空港
  { id: "tr-air-1", domain: "travel", ja: "この便のゲートはどこですか？", en: "Which gate does this flight leave from?" },
  { id: "tr-air-2", domain: "travel", ja: "乗り継ぎなんですが、間に合いますか？", en: "I've got a connecting flight — will I make it?" },
  // 荷物（深く確認）
  { id: "tr-bag-1", domain: "travel", ja: "荷物は羽田までスルーですか？それともここで受け取り？", en: "Is my bag checked through to Haneda, or do I need to pick it up here?" },
  { id: "tr-bag-2", domain: "travel", ja: "乗り継ぎの間、荷物は勝手に運ばれます？何かやることは？", en: "Does my bag get transferred automatically, or do I need to do anything?" },
  { id: "tr-bag-3", domain: "travel", ja: "もし間に合わなくても、羽田で受け取れますか？", en: "If it doesn't make it, can I still pick it up at Haneda?" },
  // 支払い・買い物・食事
  { id: "tr-pay-1", domain: "travel", ja: "カードで払えますか？", en: "Can I pay by card?" },
  { id: "tr-pay-2", domain: "travel", ja: "おすすめは？", en: "What do you recommend?" },
  { id: "tr-pay-3", domain: "travel", ja: "お会計お願いします。", en: "Can we get the check?" },
  { id: "tr-beer-1", domain: "travel", ja: "ビールは何がありますか？軽めのと、しっかりめのと。", en: "What beers do you have? Anything light, or something a bit stronger?" },
  { id: "tr-beer-2", domain: "travel", ja: "地元のビールってあります？何が違うんですか？", en: "Do you have any local beers? What's the difference between them?" },
  // 旅仲間との雑談
  { id: "tr-chat-1", domain: "travel", ja: "どちらから来たんですか？", en: "So, where are you from?" },
  { id: "tr-chat-2", domain: "travel", ja: "何しに来たんですか？（旅の目的）", en: "What brings you here?" },
  { id: "tr-chat-3", domain: "travel", ja: "へえ、面白い！もっと聞かせて。", en: "Oh, interesting. Tell me more!" },
  { id: "tr-chat-4", domain: "travel", ja: "日本から来ました。子どもの医者で、お腹と栄養が専門です。", en: "I'm from Japan. I'm a children's doctor, and I focus on gut health and nutrition." },
  { id: "tr-chat-5", domain: "travel", ja: "また連絡取れたら。番号交換しません？", en: "Let's keep in touch — want to swap numbers?" },
  { id: "tr-chat-6", domain: "travel", ja: "会えてよかった。良い旅を！", en: "Really nice meeting you — safe travels!" },
  // 聞き取れない時
  { id: "tr-rec-1", domain: "travel", ja: "ごめん、もう一回いい？", en: "Sorry, say that again?" },
  { id: "tr-rec-2", domain: "travel", ja: "つまり、〜ってこと？", en: "So you mean ___, right?" },
  { id: "tr-rec-3", domain: "travel", ja: "それ、どういう意味ですか？", en: "What does that mean?" },
  // 機内（客室乗務員とのやりとり）
  { id: "tr-cabin-1", domain: "travel", ja: "毛布をもらえますか？", en: "Could I get a blanket?" },
  { id: "tr-cabin-2", domain: "travel", ja: "お水をもらえますか？", en: "Could I get some water?" },
  { id: "tr-cabin-3", domain: "travel", ja: "食事は何がありますか？", en: "What are the meal options?" },
  { id: "tr-cabin-4", domain: "travel", ja: "すみません、通してもらえますか？", en: "Excuse me, could I get through?" },
  { id: "tr-cabin-5", domain: "travel", ja: "席を倒してもいいですか？", en: "Is it okay if I recline my seat?" },
  { id: "tr-cabin-6", domain: "travel", ja: "入国カードをもう一枚もらえますか？", en: "Could I get another arrival card?" },
  // ショップ（買い物）
  { id: "tr-shop-1", domain: "travel", ja: "これ、試着できますか？", en: "Can I try this on?" },
  { id: "tr-shop-2", domain: "travel", ja: "もう少し大きいサイズはありますか？", en: "Do you have this in a bigger size?" },
  { id: "tr-shop-3", domain: "travel", ja: "これ、いくらですか？", en: "How much is this?" },
  { id: "tr-shop-4", domain: "travel", ja: "見ているだけです、ありがとう。", en: "I'm just looking, thanks." },
  { id: "tr-shop-5", domain: "travel", ja: "別の色はありますか？", en: "Do you have this in another color?" },
  { id: "tr-shop-6", domain: "travel", ja: "プレゼント用に包んでもらえますか？", en: "Could you gift-wrap this for me?" },
  // 道・移動・タクシー
  { id: "tr-way-1", domain: "travel", ja: "駅はどっちですか？", en: "Which way is the station?" },
  { id: "tr-way-2", domain: "travel", ja: "（タクシーで）この住所までお願いします。", en: "Could you take me to this address?" },
  { id: "tr-way-3", domain: "travel", ja: "ここで停めてください。", en: "Could you stop here, please?" },
  // 体調不良を伝える（旅先）
  { id: "tr-sick-1", domain: "travel", ja: "気分が悪いんです。", en: "I'm not feeling well." },
  { id: "tr-sick-2", domain: "travel", ja: "頭が痛いです。", en: "I have a headache." },
  { id: "tr-sick-3", domain: "travel", ja: "お腹を壊しました。", en: "I have an upset stomach." },
  { id: "tr-sick-4", domain: "travel", ja: "子どもが熱があります。", en: "My child has a fever." },
  { id: "tr-sick-5", domain: "travel", ja: "近くに病院か薬局はありますか？", en: "Is there a hospital or a pharmacy nearby?" },
  { id: "tr-sick-6", domain: "travel", ja: "ナッツのアレルギーがあります。", en: "I have a nut allergy." },
  // 薬局
  { id: "tr-pharm-1", domain: "travel", ja: "頭痛に効くものはありますか？", en: "Do you have anything for a headache?" },
  { id: "tr-pharm-2", domain: "travel", ja: "子ども用の解熱剤はありますか？", en: "Do you have fever medicine for kids?" },
  { id: "tr-pharm-3", domain: "travel", ja: "これは1日何回飲みますか？", en: "How many times a day do I take this?" },
  // トラブル（紛失・遅延）
  { id: "tr-trb-1", domain: "travel", ja: "荷物が出てこないんです。", en: "My bag hasn't come out." },
  { id: "tr-trb-2", domain: "travel", ja: "財布をなくしました。", en: "I've lost my wallet." },
  { id: "tr-trb-3", domain: "travel", ja: "飛行機が遅れています。どうすればいいですか？", en: "My flight is delayed — what should I do?" },
  { id: "tr-trb-4", domain: "travel", ja: "助けてください。", en: "I need some help." },
  // 交通（電車・バス・地下鉄）
  { id: "tr-trn-1", domain: "travel", ja: "この電車、〜に行きますか？", en: "Does this train go to ___?" },
  { id: "tr-trn-2", domain: "travel", ja: "切符はどこで買えますか？", en: "Where can I buy a ticket?" },
  { id: "tr-trn-3", domain: "travel", ja: "〜へは、何番線ですか？", en: "Which platform is it for ___?" },
  { id: "tr-trn-4", domain: "travel", ja: "次のバスは何時ですか？", en: "What time's the next bus?" },
  { id: "tr-trn-5", domain: "travel", ja: "〜で降りたいんです。着いたら教えてもらえますか？", en: "I want to get off at ___ — could you let me know when we're there?" },
  // 観光・チケット・写真
  { id: "tr-sight-1", domain: "travel", ja: "大人2枚、子ども1枚ください。", en: "Two adults and one child, please." },
  { id: "tr-sight-2", domain: "travel", ja: "何時まで開いていますか？", en: "How late are you open?" },
  { id: "tr-sight-3", domain: "travel", ja: "中で写真を撮ってもいいですか？", en: "Is it okay to take photos inside?" },
  { id: "tr-sight-4", domain: "travel", ja: "写真を撮ってもらえますか？", en: "Could you take a photo of us?" },
  // お金・両替・チップ
  { id: "tr-money-1", domain: "travel", ja: "これを両替できますか？", en: "Can I exchange this?" },
  { id: "tr-money-2", domain: "travel", ja: "近くにATMはありますか？", en: "Is there an ATM nearby?" },
  { id: "tr-money-3", domain: "travel", ja: "チップは必要ですか？", en: "Do I need to leave a tip?" },
  // レストラン（予約・詳細）
  { id: "tr-rest-1", domain: "travel", ja: "今夜、2名で予約できますか？", en: "Can I book a table for two tonight?" },
  { id: "tr-rest-2", domain: "travel", ja: "窓際の席はありますか？", en: "Could we get a table by the window?" },
  { id: "tr-rest-3", domain: "travel", ja: "これ、ナッツは入っていますか？", en: "Does this have any nuts in it?" },
  { id: "tr-rest-4", domain: "travel", ja: "取り分け用の小皿をもらえますか？", en: "Could we get some extra plates to share?" },
  { id: "tr-rest-5", domain: "travel", ja: "これ、持ち帰りできますか？", en: "Can I get this to go?" },
  // カフェ・Wi-Fi
  { id: "tr-cafe-1", domain: "travel", ja: "Wi-Fiは使えますか？パスワードは？", en: "Do you have Wi-Fi? What's the password?" },
  { id: "tr-cafe-2", domain: "travel", ja: "ここ、少し座ってもいいですか？", en: "Is it okay if I sit here for a bit?" },
  // 緊急・紛失
  { id: "tr-emg-1", domain: "travel", ja: "警察を呼んでもらえますか？", en: "Could you call the police?" },
  { id: "tr-emg-2", domain: "travel", ja: "日本大使館はどこですか？", en: "Where is the Japanese embassy?" },
  // 雑談・つかみ
  { id: "tr-sm-1", domain: "travel", ja: "今日はいい天気ですね。", en: "Lovely weather today, isn't it?" },
  { id: "tr-sm-2", domain: "travel", ja: "このあたりで、おすすめの場所はありますか？", en: "Any spots around here you'd recommend?" },
  { id: "tr-sm-3", domain: "travel", ja: "写真、撮りましょうか？", en: "Want me to take a photo for you?" },
  // 言い回しのバリエーション（同じ意図・別の言い方）
  { id: "tr-var-1", domain: "travel", ja: "（お会計・別の言い方）お勘定お願いします。", en: "Could we get the bill, please?" },
  { id: "tr-var-2", domain: "travel", ja: "（ありがとう・くだけて）ほんと助かりました！", en: "Thanks so much — you're a lifesaver!" },
  { id: "tr-var-3", domain: "travel", ja: "（ごめん・軽く）あ、すみません！", en: "Oh, sorry about that!" },
  { id: "tr-var-4", domain: "travel", ja: "（もう一回・くだけて）ごめん、なんて言った？", en: "Sorry, what was that?" },
  // 道案内をする（人を助ける側）— 羽田→成田
  { id: "tr-dir-1", domain: "travel", ja: "はい、この電車で大丈夫です。方向も合っていますよ。", en: "Yes, this train is fine — you're heading the right way." },
  { id: "tr-dir-2", domain: "travel", ja: "ただ、快速と各駅停車があります。早く行きたいなら快速に乗ってください。", en: "There are rapid and local trains, though — if you want to get there faster, take the rapid one." },
  { id: "tr-dir-3", domain: "travel", ja: "まず浜松町まで行って、そこで山手線に乗り換えます。", en: "First, go to Hamamatsuchō and change to the Yamanote Line there." },
  { id: "tr-dir-4", domain: "travel", ja: "山手線で、上野方面に乗って日暮里まで行きます。", en: "Take the Yamanote Line toward Ueno, and go as far as Nippori." },
  { id: "tr-dir-5", domain: "travel", ja: "日暮里で、成田空港行きの電車（京成線）に乗り換えます。", en: "At Nippori, change to the train for Narita Airport — the Keisei Line." },
  { id: "tr-dir-6", domain: "travel", ja: "全部で1時間半くらいです。", en: "It takes about an hour and a half in all." },
  { id: "tr-dir-7", domain: "travel", ja: "乗り換えを減らしたいなら、京急線の直通電車もあります（本数は少なめです）。", en: "If you'd rather have fewer transfers, some Keikyu trains go straight through to Narita." },

  // ── 🔖 保存（院長が「これ英語で」と言い、Claudeが英訳して入れたもの）──
  { id: "mine-1", domain: "mine", ja: "後ろから人が来てるから、少し早く歩こう。", en: "Someone's coming up behind us — let's walk a little faster." },
  { id: "mine-2", domain: "mine", ja: "今日は一日曇りだけど、今日も含めて今週は雨が降りやすいみたいだよ。", en: "It's going to be cloudy all day today, but it looks like we're in for a rainy week — today included." },
  // 乗り継ぎ便の荷物を途中（フランクフルト）で受け取る＝院長の実戦（2026-09-27）。2文をひとかたまりで覚える
  { id: "mine-3", domain: "mine", ja: "この荷物はいったんフランクフルトで受け取りたいので、フランクフルトまで預けてください。", en: "We'd like to collect our baggage in Frankfurt first. So, please check our baggage only to Frankfurt." },
  { id: "mine-4", domain: "mine", ja: "フランクフルトに2泊します。", en: "We're staying in Frankfurt for two nights." },
  { id: "mine-5", domain: "mine", ja: "日本までスルーで預けないでください。", en: "Please don't check our baggage through to Japan." },
  { id: "mine-6", domain: "mine", ja: "2個ともフランクフルトで受け取れますか？", en: "Can we collect both of our bags in Frankfurt?" },
  { id: "mine-7", domain: "mine", ja: "一日、雨が降ったりやんだりするみたいです。今日も含めて今週はずっと、雨が降りやすい状態が続くみたいです。", en: "It looks like it’s going to rain on and off all day. And this whole week looks rainy, today included." },
];
