/* Hanaseru 🧱 喋り始めの型 — 辞書の中で繰り返し使っている「文の入り方」だけを取り出し、ミニ解説を付ける
   院長 2026-09-29「共通して使う喋り始めの型がある。文法的にどうなっているか、アメリカ人はよく使うのか、
   ミニ解説があると安心して進める」。カードの通常画面には解説を出さない方針のまま、型だけはこの画面で解説する。
   例文は辞書から自動で拾う（re に当たる札）＝辞書が育つと例も増える。 */
window.HANASERU_PATTERNS = [
  { id: "p-could-you", kata: "Could you ～?", ja: "〜してもらえますか？（お願い）",
    why: "お願いの王道。Can you より少しやわらかく、丁寧すぎない。アメリカでもイギリスでも一番よく使う。動詞は原形。最後に please を付けるとさらにやわらかい。",
    re: /^Could you\b/ },
  { id: "p-could-i", kata: "Could I ～? / Can I ～?", ja: "〜してもいいですか？（自分がすることの許可・依頼）",
    why: "自分が何かしたい・もらいたいときの入り方。Could I get some water? のように get と組むと万能。Can I でも失礼ではない。",
    re: /^(Could|Can) I\b/ },
  { id: "p-could-we", kata: "Could we ～? / Can we ～?", ja: "私たち〜できますか？（家族・連れがいるとき）",
    why: "一人旅なら I、家族連れなら we。それだけの違い。レストラン・ホテル・空港で we を使うと、自然に「家族で」が伝わる。",
    re: /^(Could|Can) we\b/ },
  { id: "p-do-you", kata: "Do you have ～?", ja: "〜はありますか？",
    why: "店・ホテル・診察室、どこでも使う質問の型。Do you have + 名詞。Is there ～? も同じ意味で使える。",
    re: /^Do you (have|need|mean)\b/ },
  { id: "p-if-she", kata: "If ～, please ～. / If ～, call ～.", ja: "もし〜なら、〜してください（目安を伝える）",
    why: "診療の説明の背骨。If の中は現在形（If the fever doesn't come down）、後ろは please か命令形。未来のことでも If の中は will を使わない。これが英語の決まり。",
    re: /^If (she|the|it|things|you|that)\b/ },
  { id: "p-lets", kata: "Let's ～.", ja: "〜しましょう（一緒に決める）",
    why: "Let us の短い形。医師が「一緒にやりましょう」と言うときの王道。命令に聞こえないので、親に方針を伝えるときに安心して使える。",
    re: /^Let's\b/ },
  { id: "p-let-me", kata: "Let me ～.", ja: "〜させてね／〜しますね（自分がこれからすること）",
    why: "診察で子どもに「診させてね」と言うときの型。Let me take a look. Let me listen to your chest. やわらかい宣言。",
    re: /^Let me\b/ },
  { id: "p-ill-give", kata: "I'll give you ～.", ja: "〜を出しておきます（処方）",
    why: "薬を出すときの一番簡単な言い方。prescribe より日常的で、親にもすぐ分かる。I'll = I will。",
    re: /^I'll (give|also give)\b/ },
  { id: "p-please-dont", kata: "Please don't worry.", ja: "心配いりません",
    why: "院長の署名フレーズ。There's nothing to worry about. も同じ意味。短いほうが診察室では強い。",
    re: /^(Please don't worry|There's (really )?nothing to worry)/ },
  { id: "p-its-not", kata: "It's not ～. It's ～.", ja: "〜ではありません。〜です。（誤解を解く）",
    why: "「病気ではなく体質です」のように、否定→肯定の2文で言う型。1文にまとめず、2つに切るほうが伝わる。",
    re: /^It('s| is) not\b/ },
  { id: "p-i-think", kata: "I think ～.", ja: "〜だと思います（診断・意見をやわらかく）",
    why: "断定を避けて意見を言う王道。I think it's a common cold. アメリカ人は会話でとてもよく使う。「意見＋理由」の物差し①の入り口。",
    re: /^I think\b/ },
  { id: "p-it-looks", kata: "It looks like ～.", ja: "〜みたいです／〜のようです",
    why: "見た感じ・様子からの判断。後ろは名詞（It looks like rain）でも文（It looks like it's going to rain）でもよい。'll が言いにくければ名詞の形にする。",
    re: /^(It|That) looks like\b/ },
  { id: "p-to-be-honest", kata: "To be honest, ～", ja: "正直に言うと、〜",
    why: "本音を言う前置き。Honestly, でも同じ。物差し①「意見を言う」ときに、自分の考えだと示せる。",
    re: /^(To be honest|Honestly)\b/ },
  { id: "p-so", kata: "So, ～.", ja: "だから／なので、〜",
    why: "理由と結論をつなぐ最短の語。前の文を受けて So, we'll start antibiotics. 会話では because より So のほうがよく出る。",
    re: /^So,?\s/ },
  { id: "p-first-then", kata: "First, ～. Then, ～.", ja: "まず〜。それから〜。",
    why: "手順を伝える型。長い文にせず、First / Then / After that で切る。親は順番で覚える。",
    re: /^(First|Then|After that)\b/ },
  { id: "p-how-long", kata: "How long ～?", ja: "どのくらい〜？（期間）",
    why: "3つの形＝How long have you been here?（今まで）／How long are you staying?（滞在全体）／How long does it take?（所要時間）。",
    re: /^How long\b/ },
  { id: "p-thats", kata: "That's ～.", ja: "それが〜です（前の話をまとめる）",
    why: "That's the fastest way. That's what matters. 前に言ったことを一言でまとめる型。話の締めに強い。",
    re: /^That's\b/ },
  { id: "p-you-can", kata: "You can ～.", ja: "〜して大丈夫です（許可）",
    why: "「〜していいですよ」を一番短く言う形。You can come without an appointment. It's fine to ～ も同じ。",
    re: /^(You can\b|It.s fine (to|for)|She can\b)/ }
];
