/* Reconstructed practice dialogues. No patient transcripts or identifying details.
   Clinical plans below are scenario premises, not general treatment instructions. */
(function () {
  'use strict';
  function turn(heard, heardJa, intent, en, note) { return {heard:heard, heardJa:heardJa, intent:intent, en:en, note:note}; }
  window.HANASERU_SCENES = [
    {id:'clinic-listen',track:'clinic',title:'まず、いちばん心配なことを聞く',role:'保護者',context:'発熱を心配して来院。診断を急がず、様子と心配事を聞いて診察につなげる練習。',goal:'心配を受け止め、具体的に聞き返せる',turns:[
      turn("I'm worried about my child's fever.",'子どもの熱が心配です。','心配を受け止めて、いつからか聞く。',"I can see you're worried. When did the fever start?",'共感のあとに質問を一つ。最初から長い説明を始めない。'),
      turn('It started yesterday. It went down, but then it came back.','昨日からです。いったん下がったのに、また上がりました。','熱が下がったときの様子を聞く。',"How is your child when the fever comes down? Are they playing at all?",'they は性別を決めずに子どもを指せる。実際の診療では he / she でもよい。'),
      turn("A little, but they're not eating much.",'少し遊びますが、あまり食べません。','食べられないという返事を受け、水分と尿を確認する。',"I see. Are they drinking? And are they peeing as much as usual?",'as much as usual＝普段と同じくらい。保護者への口頭では peeing で伝わる。'),
      turn("They're drinking, but peeing less. I'm scared it could be something serious.",'水分は取れていますが、尿は少なめです。重い病気ではないか心配です。','心配を理解したことを伝え、診察してから説明する。',"Thank you for telling me. Let me examine your child first. Then we'll talk about what may be causing this and what to do next.",'診察前に「大丈夫」と確約しない。first → then で次の流れを示す。')
    ],challenge:turn("I'm not sure what you mean by 'less active'.",'「元気がない」という意味がよく分かりません。','専門的でない言葉で言い換え、普段との違いを聞く。',"I mean, are they playing or talking less than usual? What changes have you noticed?",'別の言い方で確認できればOK。')},
    {id:'clinic-bowel',track:'clinic',title:'良くなった点と、まだ続ける理由',role:'保護者',context:'便秘の再診。便漏れは減ったが、今回の診察では便がまだ残っており、医師が治療継続を判断した設定。',goal:'改善を認めつつ、方針の理由を短くつなげる',turns:[
      turn("The accidents are happening less often now.",'便漏れが減ってきました。','良い変化を認めて、どのくらい変わったか聞く。',"That's good to hear. How often is it happening now?",'accidents はこの場面では便漏れ。曖昧なら stool accidents と言い換える。'),
      turn('Only once this week. Does that mean we can stop the medicine?','今週は1回だけです。薬をやめてもいいですか？','改善と、今日の診察所見をつなげて説明する。',"That's real progress. But today's exam shows there's still some stool left. So I think we should continue the treatment for now.",'for now＝今の段階では。便秘全般の指示ではなく、この設定での判断。'),
      turn("I thought fewer accidents meant everything was better.",'漏れが減ったので、もう良くなったと思いました。','そう思うのは自然だと認め、目標を共有する。',"I understand why you thought that. Fewer accidents are a good sign. We also want your child to keep passing stool regularly, so it doesn't build up again.",'否定から入らず、良い点＋まだ必要なことを並べる。'),
      turn("Okay. It's hard to keep track every day, though.",'分かりました。でも毎日全部記録するのは大変です。','負担に気づき、続けやすい方法を相談する。',"You don't have to write down every detail. Let's find a simple way to keep track. What would be manageable for you?",'manageable＝無理なくできる。簡単にするなら What would work for you?')
    ],challenge:turn('Some days are better, and some days are worse. Is the treatment failing?','良い日と悪い日があります。治療がうまくいっていないのでしょうか？','波があることと、変化を確認する必要を伝える。',"There can be ups and downs. Let's look at what's changed before we decide whether to adjust the treatment.",'断定的に安心させず、変化を一緒に確認する。')},
    {id:'clinic-nutrition',track:'clinic',title:'栄養の話を、無理のない一歩へ',role:'保護者',context:'疲れやすさの相談。栄養だけで原因を決めず、生活も聞きながら実行できる一歩を相談する。',goal:'一つの可能性を説明し、相手と小さな目標を決める',turns:[
      turn("My child is tired all the time. Could it be the food?",'いつも疲れています。食事のせいでしょうか？','食事は一つの視点と伝え、生活を聞く。',"Food may be part of the picture, but it may not explain everything. Could you walk me through a typical day, including meals and sleep?",'walk me through＝順を追って教えて。nutrition がすべての原因とはしない。'),
      turn('Breakfast is often just something sweet. Mornings are so busy.','朝は甘いものだけになりがちです。忙しくて。','忙しさを受け止め、「禁止」より足す提案をする。',"Mornings can be hard. Rather than changing everything at once, let's think about adding something. What foods does your child enjoy?",'まず好きな食べ物を聞くと、押しつけではなく相談になる。'),
      turn('Yogurt is usually okay. Do we have to stop all sweets?','ヨーグルトなら食べます。甘いものは全部やめないといけませんか？','全部を一度に変えず、できそうな一歩を一緒に決める。',"We don't need to change everything today. If yogurt works for your child, could you try adding it to breakfast? Let's start with something you can keep doing.",'この会話ではヨーグルトを食べられる設定。個別の食物アレルギーなどは実際の診療で確認する。'),
      turn('Will that get rid of the tiredness?','それで疲れやすさは治りますか？','改善を約束せず、他の原因も含めて見る姿勢を伝える。',"I can't promise that. It's one way to support your child's health while we look at other possible causes. Let's review how things are going at the next visit.",'support＝支える。食事だけで治るとは言わず、次の確認につなげる。')
    ],challenge:turn("We've tried lots of things already. I'm not sure we can do more.",'もういろいろ試していて、これ以上できるか分かりません。','努力を認め、増やす前に困り事を聞く。',"You've already put a lot of effort into this. Before we add anything, what's been hardest for you?",'助言を増やす前に、負担を聞く。')},
    {id:'clinic-plan',track:'clinic',title:'家庭で続けられる計画にする',role:'保護者',context:'診察を終えて治療計画を相談中。来院や日々の実行が負担になっている保護者と、困り事を整理する。',goal:'事情を聞き、説明の伝わり方を確認して終える',turns:[
      turn("I'm not sure we can follow this plan at home.",'家でこの計画を続けられるか自信がありません。','率直に話してくれたことに感謝し、困る部分を聞く。',"Thank you for telling me. Which part feels hardest to manage?",'「頑張って」だけで終えず、具体的な障害を聞く。'),
      turn('Coming back so often is difficult because of work.','仕事があるので、頻繁に来るのが難しいです。','事情を認め、安全に可能な選択肢を相談する。',"I understand. Let's see what follow-up options are suitable for your child and work for your family.",'通院不要やオンライン可と約束せず、適した選択肢を検討する。'),
      turn("I also forget what I'm supposed to watch for.",'何に気をつけるのかも忘れてしまいます。','個別の注意点を書いて、一緒に確認する提案。',"Let's write down the key things to watch for and when to get help. We can go through them together.",'実際には症状に応じた注意点を記入する。これだけで帰宅説明が完結するわけではない。'),
      turn('That would help. I think I understand now.','助かります。分かったと思います。','自分の説明が伝わったか、相手の言葉で確かめる。',"Just so I know I've explained it clearly, could you tell me what you'll do when you get home?",'相手をテストする言い方ではなく、自分の説明が十分だったか確認する。')
    ],challenge:turn('Could you say that in simpler words?','もっと簡単な言葉で言ってもらえますか？','自分が今説明したことを、一つだけ簡単に言い直す。',"Of course. Let's take it one step at a time. First, let's check what you need to do today.",'この手本に続けて、その日の計画を自分の言葉で一つ補う。')},
    {id:'de-hotel',track:'travel',title:'ホテルで用事を済ませる',role:'ホテルのスタッフ',context:'12月のドイツ滞在。ホテルでチェックインし、静かな部屋を相談する。日数や名前は自分の予約に合わせる。',goal:'希望と理由を伝え、希望どおりでない場合も相談する',turns:[
      turn('Good evening. How can I help you?','こんばんは。ご用件は？','予約名と2泊のチェックインを伝える。',"I'd like to check in. I have a reservation under Komori for two nights.",'under ＋名前＝その名前で予約している。'),
      turn('May I see your passport, please?','パスポートを見せていただけますか？','渡しながら、静かな部屋を希望する理由を添える。',"Of course. Here you are. Would it be possible to have a quiet room? I'm a light sleeper.",'light sleeper＝物音などで目が覚めやすい人。理由は自分の事情に変えてよい。'),
      turn('We only have rooms facing the street tonight.','今夜は通り側の部屋しかありません。','別の選択肢を相談する。',"I see. Do you have one on a higher floor? If not, could we check again tomorrow?",'希望が通らないときは別案＋難しい場合の確認。'),
      turn('I can offer you a room on the fifth floor. Breakfast is downstairs.','5階の部屋をご案内できます。朝食は下の階です。','提案に返事をし、朝食の時間と料金込みかを確認する。',"That sounds good, thank you. What time is breakfast, and is it included in my booking?",'食事付きかどうかは決めつけずに確認する。')
    ],challenge:turn('There is an extra charge for that room.','その部屋には追加料金がかかります。','金額を聞き、決める前に考える時間を取る。',"How much extra would it be for the two nights? Let me think about it for a moment.",'値段を理解してから決める。')},
    {id:'de-train',track:'travel',title:'列車を確かめ、変更にも対応する',role:'駅のスタッフ',context:'ドイツで目的地の駅名をスマートフォンに表示して相談。ホーム番号や運賃は練習用の返事で、実際の案内ではない。',goal:'目的地・乗り換え・切符の条件を確認する',turns:[
      turn('Where would you like to go?','どちらまでですか？','画面の目的地へ行きたいと伝え、列車を聞く。',"I'd like to get to this station. Could you tell me which train to take?",'this station と画面を指すことで、地名が言いにくくても伝えられる。'),
      turn('You can take the next train, but you need to change once.','次の列車で行けますが、1回乗り換えが必要です。','どこで乗り換えるか、見える形で教えてもらう。',"Where do I change trains? Could you show me on the map?",'聞き取るだけに頼らず、地図を一緒に見る。'),
      turn('At the next station. Do you already have a ticket?','次の駅です。切符はお持ちですか？','持っている切符が使えるか確認する。',"Yes, I have this ticket. Is it valid for that train, or do I need a different one?",'valid for＝その列車に使える。切符の規則は種類ごとに確認する。'),
      turn('This ticket is valid. The train leaves from platform four.','この切符で大丈夫です。4番ホームからです。','番号と乗り換えを復唱して、認識を合わせる。',"Platform four, and I change at the next station. Is that right? Thank you for your help.",'数字と行動を復唱する。実際のホーム番号は当日の案内で確認。')
    ],challenge:turn('That train has been cancelled.','その列車は運休になりました。','次の手段と手持ちの切符が使えるかを尋ねる。',"What's the next option for getting there? Can I use this ticket, or do I need to change it?",'代替手段を聞き、切符の扱いも確認する。')},
    {id:'de-food',track:'travel',title:'食事を選び、会計する',role:'店員',context:'レストランで地元の料理を相談する。食の好みを一つ伝え、最後は会計まで。',goal:'おすすめに条件を添え、相手の提案に返す',turns:[
      turn('Are you ready to order?','ご注文はお決まりですか？','地元の料理を試したいと伝え、おすすめを聞く。',"I'd like to try something local. What would you recommend?",'local＝その土地の。'),
      turn('The sausage platter is popular. Would you like that?','ソーセージの盛り合わせが人気です。いかがですか？','量を確かめる。',"That sounds nice. Is it a large portion? I'm not very hungry.",'感想→確認→理由。提案に無言で別の質問を重ねない。'),
      turn('It is quite large, but we can do a smaller portion.','かなり多いですが、小さめにもできます。','提案を受け、飲み物も頼む。',"A smaller portion would be great, thank you. And could I have some still water, please?",'still water＝炭酸なしの水。無料とは限らないので必要なら値段も聞く。'),
      turn('Did you enjoy your meal?','お料理はいかがでしたか？','感想を述べて、会計と支払い方法を聞く。',"Yes, it was lovely. Could I have the bill, please? And can I pay by card?",'bill は会計。カードが使えるかは店ごとに確認。')
    ],challenge:turn("I'm sorry, we've run out of that dish.",'申し訳ありませんが、その料理は売り切れです。','別のおすすめを希望の条件付きで聞く。',"No problem. What else would you recommend that's not too heavy?",'希望を少し変えてやり取りを続ける。')},
    {id:'de-bags',track:'travel',title:'荷物を預け、受け取りを確認する',role:'ホテルのスタッフ',context:'チェックアウト後、出発まで街を歩きたい。ホテルに荷物を預けられるか相談する。',goal:'依頼・時間・受け取り場所を確認する',turns:[
      turn('Are you checking out now?','今からチェックアウトですか？','チェックアウトし、荷物を預けたい理由を伝える。',"Yes, please. My flight is later today. Could I leave my bags here while I look around the city?",'while＝街を見ている間。理由があると依頼が伝わりやすい。'),
      turn('How many bags do you have?','お荷物はいくつですか？','個数を伝えて料金を確認する。',"Two bags. Is there a charge for storing them?",'無料・有料を決めつけない。'),
      turn('There is no charge. What time will you collect them?','料金はかかりません。何時に受け取りますか？','練習では午後4時と伝え、可能か確認する。',"Around four this afternoon. Would that be okay?",'around＝およそ。時刻は実際の旅程に合わせる。'),
      turn("That's fine. Please keep this ticket.",'大丈夫です。この控えを保管してください。','控えを受け取り、受け取り場所を確認する。',"Thank you. Do I come back to this desk to collect them?",'them は預けた荷物。受け取り方まで確認して終える。')
    ],challenge:turn("I'm afraid we can't store bags here.",'ここでは荷物を預かれません。','代わりに預けられる場所を尋ねる。',"I understand. Do you know somewhere nearby where I can leave them?",'断られても、次の手段を相談できれば会話は前に進む。')},
    {id:'de-repair',track:'travel',title:'聞き取れないときも、止まらず相談する',role:'街で道を尋ねた相手',context:'道案内が速くて聞き取れない。地図を使い、一つずつ確認する。',goal:'ゆっくり・別の言葉・見える情報をお願いする',turns:[
      turn("Go past the square, take the second left, and it's opposite the pharmacy.",'広場を過ぎて2本目を左、薬局の向かいです。','聞き取れなかったので、ゆっくりもう一度お願いする。',"Sorry, I didn't catch all of that. Could you say it again a little more slowly?",'全部分からなかったと具体的に言えば、相手も調整しやすい。'),
      turn("Walk past the square first. Do you know where the square is?",'まず広場を過ぎます。広場の場所は分かりますか？','分からないことを伝え、地図を見せる。',"Not really. Could you show me here on the map?",'知っているふりをせず、Not really で自然に助けを求める。'),
      turn("Here. Then take the second street on your left.",'ここです。その後、左側の2本目の道です。','2本目で合っているかを確認する。',"The second street, not the first. Is that right?",'聞き間違えやすい点だけを短く確認する。'),
      turn("That's right. The building is just across from the pharmacy.",'そうです。建物は薬局のすぐ向かいです。','理解した道順をまとめ、お礼を言う。',"Got it. Past the square, then the second left. Thank you for taking the time to help me.",'全文を完璧に復唱する必要はなく、重要な行動を確かめる。')
    ],challenge:turn("I'm sorry, I don't speak much English.",'すみません、英語はあまり話せません。','地図や翻訳アプリを使う提案をする。',"That's okay. Could we use this map, or a translation app?",'英語だけで押し通す必要はない。')},
    {id:'de-chat',track:'travel',title:'自己紹介から、もう一往復',role:'滞在先で知り合った人',context:'短い雑談。自分の仕事や関心を一言足し、相手にも質問して会話を続ける。',goal:'自分のこと＋理由＋相手への質問を言える',turns:[
      turn('Are you visiting Germany on holiday?','休暇でドイツに来ているんですか？','2泊の滞在だと伝え、相手のことも聞く。',"Yes, I'm staying for two nights before flying back to Japan. Do you live around here?",'旅行目的が違う場合は最初の一文を自分の事情に変える。'),
      turn('Yes, I do. What do you do in Japan?','はい、近くに住んでいます。日本ではどんなお仕事を？','小児外科医であることと、家族への関わりを伝える。',"I'm a pediatric surgeon. I also see children and their families at my clinic. I enjoy helping parents feel more confident about caring for their children.",'肩書きだけで終えず、自分が大切にしていることを足す。'),
      turn('That sounds rewarding. What would you like to see while you are here?','やりがいがありそうですね。滞在中は何を見たいですか？','日常の暮らしに関心があると伝え、おすすめを聞く。',"I'd like to get a feel for everyday life here, not just the famous sights. Is there a place you like to go on your day off?",'get a feel for＝雰囲気を感じる。自分の関心に変えて話す練習。'),
      turn("I like the local market. It's a nice place to walk around.",'地元の市場が好きです。歩くのにいい所ですよ。','相手のおすすめに反応し、具体的な質問を返す。',"That sounds like my kind of place. What's your favorite thing about it?",'「いいですね」で終わらず、相手の好きな理由を聞く。')
    ],challenge:turn('What do you enjoy most about your work?','仕事のどんなところがいちばん好きですか？','自分の経験を一つ足して、好きな理由を話す。',"I enjoy seeing a child feel better and a parent look relieved. It makes the work feel worthwhile.",'手本の理由が自分と違えば、自分の理由で答える。')},
    {id:'de-airport',track:'travel',title:'帰国便と荷物の行き先を確認する',role:'空港のスタッフ',context:'ドイツから帰国する空港。予約画面を見せ、乗り継ぎと預け荷物の扱いを確認する。直行便なら自分の旅程に変える。',goal:'分からない条件を、推測せず確認する',turns:[
      turn('May I see your booking and passport?','予約とパスポートを見せてください。','提示して、帰国することを伝える。',"Here you are. I'm flying back to Japan today. Could you check my booking, please?",'具体的な便名を言いにくければ予約画面を見せる。'),
      turn('You have a connecting flight. Are you checking this bag?','乗り継ぎがあります。この荷物は預けますか？','荷物を預け、最終目的地まで運ばれるか確認する。',"Yes, please. Will it be checked through to my final destination, or do I need to collect it during the connection?",'checked through＝最終目的地まで預ける。経路ごとに確認する。'),
      turn('It will be checked through. Here are your boarding passes.','最終目的地まで運ばれます。こちらが搭乗券です。','理解を確かめて、乗り継ぎ案内をどこで見られるか聞く。',"So I don't need to collect it during the connection. Is that right? Where can I check the gate for my next flight?",'荷物の説明は、この練習内でのスタッフの返答。実際の予約にも当てはまるとは限らない。'),
      turn('Check the screens when you arrive. The gate may change.','到着後、案内画面で確認してください。ゲートが変わることがあります。','分かったことを返し、困ったときの相談先を聞く。',"Okay, I'll check the screens. If my first flight is delayed, who should I speak to about the connection?",'予定が変わったときの相談先まで聞いておく。')
    ],challenge:turn('Your bag needs to be collected and checked in again.','荷物を受け取り、もう一度預ける必要があります。','どこで何をするのか、順番に教えてもらう。',"Could you explain where I collect it and where I check it in again? I'd like to make sure I understand the steps.",'前と違う返答でも、相手の情報に合わせて確認する。')}
  ];
})();
